<?php

require_once dirname(__FILE__).'/../../../src/yuki-request/yRequest.php';

/**
 * Test class for yRequest.
 * Generated by PHPUnit on 2011-04-01 at 02:01:05.
 */
class yRequestTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yRequest
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        $this->object = new yRequest;
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    /**
     * @todo Implement testAll().
     */
    public function testPost(){
        $request = new yRequest();
        $request->setPost(array('a'=>'b'));
        $this->assertEquals('b', $request->getPost('b'));
    }
    public function testCli(){
        $request = new yRequest();
        $this->assertEquals(true, $request->isCli()); // phpunit is called from console
        $request->setCli(false);
        $this->assertEquals(false, $request->isCli());
    }
}

